name: Micronaut CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Use Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          java-package: jdk
      - name: Set environment variables
        run: |
          echo "ISSUER=https://issuer.com" >> $GITHUB_ENV
          echo "CLIENT_ID=clientId" >> $GITHUB_ENV
          echo "CLIENT_SECRET=clientSecret" >> $GITHUB_ENV
      - name: Build and test
        run: mvn -B -ntp verify
